// <auto-generated />
namespace entity.code.first.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MusteriUnvaniMusteriSoyadi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MusteriUnvaniMusteriSoyadi));
        
        string IMigrationMetadata.Id
        {
            get { return "202211251454151_MusteriUnvaniMusteriSoyadi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
